# Generated by Django 4.1.7 on 2023-04-17 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shoppingapp", "0003_student"),
    ]

    operations = [
        migrations.RenameModel(old_name="Student", new_name="product",),
    ]
