# Generated by Django 4.1.7 on 2023-04-17 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shoppingapp", "0005_usermember_category"),
    ]

    operations = [
        migrations.RemoveField(model_name="usermember", name="category",),
    ]
