# Generated by Django 4.1.7 on 2023-04-17 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("shoppingapp", "0006_remove_usermember_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="usermember",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="shoppingapp.category",
            ),
        ),
    ]
