# Generated by Django 4.1.7 on 2023-04-17 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shoppingapp", "0007_usermember_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(default="", max_length=255),
        ),
    ]
