# Generated by Django 4.1.7 on 2023-04-17 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shoppingapp", "0008_alter_category_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category", name="name", field=models.CharField(max_length=255),
        ),
    ]
