# Generated by Django 4.1.7 on 2023-04-17 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shoppingapp", "0009_alter_category_name"),
    ]

    operations = [
        migrations.RemoveField(model_name="product", name="name",),
    ]
