# Generated by Django 4.1.7 on 2023-04-17 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shoppingapp", "0011_remove_product_image_product_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="usermember",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="image/"),
        ),
    ]
