# Generated by Django 4.1.7 on 2023-04-17 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shoppingapp", "0012_usermember_image"),
    ]

    operations = [
        migrations.RemoveField(model_name="usermember", name="image",),
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="image/"),
        ),
    ]
