# Generated by Django 4.1.7 on 2023-04-17 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shoppingapp", "0015_cart"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart", name="quantity", field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="cart",
            name="image",
            field=models.ImageField(upload_to="images/"),
        ),
        migrations.AlterField(
            model_name="cart", name="name", field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="cart",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
